#!/bin/bash

# run source.cpp in.txt out.txt expeteced.txt
# To be placed in /usr/local/bin

source=$1
path="${source%/*}"
exe="${source%%.*}.exe"
in=$2
out=$3
expected=$4

if [ $path == $source ]
then
    path="./"
else
    path=$path/
fi

if [ -z $in ]
then in="${path}in.txt"
fi

if [ -z $out ]
then out="${path}out.txt"
fi

if [ -z $expected ]
then expected="${path}expected.txt"
fi

if [ -z $source ]
then 
    echo "Where .cpp?"
    exit 0
elif [ ! -f $source ]
then 
    echo "No such file: $source"
    exit 0
elif [ ! -f $in ]
then 
    echo "where $in?"
    exit 0
fi


echo Compiling...
g++ -o "$exe" -std=c++23 -DLOCAL -Wl,-z,stack-size=256000000 $source

if [ $? != 0 ]
then exit $?
fi

echo Running...
./"$exe" < $in > $out

rm $exe


# TODO compare out.txt to expected.txt

if [ ! -f $expected ]
then exit 0
fi

echo "Comparing program's output with expected output..."
diff $out $expected -s --strip-trailing-cr --unchanged-line-format="" --old-line-format="[expected at %dn] %L" --new-line-format="[atual    at %dn] %L"