#!/bin/bash

# run source.cpp in.txt out.txt expected.txt
# To be placed in /usr/local/bin

source=$1
path="${source%/*}"
exe="${source%%.*}.exe"
in=$2
out=$3
expected=$4

compile() {
    echo "Compiling..."
    g++ $1 -o "$2" -std=c++23 -DCOTATO -Wl,-z,stack-size=256000000 -O2
}

run() {
    echo "Running..."
    if [ -z $2 ]; then
        ./"$1"
    else
        ./"$1" <$2 >$3
    fi
    rm $1
}

if [ $path == $source ]; then
    path="./"
else
    path=$path/
fi

if [[ $2 == "-p" ]]; then
    compile $source $exe
    if [ $? != 0 ]; then
        exit $?
    fi
    run $exe
    exit
fi

if [ -z $in ]; then
    in="${path}in.txt"
fi

if [ -z $out ]; then
    out="${path}out.txt"
fi

if [ -z $expected ]; then
    expected="${path}expected.txt"
fi

if [ -z $source ]; then
    echo "Where .cpp?"
    exit 0
elif [ ! -f $source ]; then
    echo "No such file: $source"
    exit 0
elif [ ! -f $in ]; then
    echo "where $in?"
    exit 0
fi

compile $source $exe

if [ $? != 0 ]; then
    exit $?
fi

run $exe $in $out

if [ ! -f $expected ]; then
    exit 0
fi

echo "Comparing program's output with expected output..."
diff $out $expected -s --strip-trailing-cr --unchanged-line-format="" --old-line-format="[expected at %dn] %L" --new-line-format="[atual    at %dn] %L"
